### ISSUE TITLE
アプリケーションが終了できなくなる(操作を受け付けなくなる)

### ISSUE THREAD

**Issue by toyoshi** [mzp/tumblotte#2]
<img width="532" alt="2016-01-20 10 09 12" src="https://cloud.githubusercontent.com/assets/188394/12437265/c266d910-bf5f-11e5-913c-567eeff15d50.png">

`Cmd+w`でウインドウを閉じたら、`Cmd+Q`でアプリケーションが終了できなくなりました。
`Cmd+N`などの操作をしても同じエラーが表示されます。

**Comment by toyoshi** [comment]
MarkdownのプレビューにあるURLをクリックしたあとも同じように操作ができなくなります。
(別件ですがURLをクリックすると画面全体がブラウザになり元に戻せない)

**Comment by mzp** [comment]
https://github.com/mzp/tumblotte/releases/tag/0.1.1

修正しました!!
